# Deployment Notes:
# For OSX: To run executable after download requires removing the extended attributes via xattr -r -c <path to exe/app>

name: anonymizer-test-build-upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: "3.11"

    - name: set env.version
      run: |
        python src/set_gha_env.py
      
    - name: Create Release
      if: "!contains(env.version, 'RC')"
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  
  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-12, ubuntu-20.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: "3.11"

    - name: Install pipenv for virtual environment
      run: |
          pip install pipenv

    - name: Install dependencies including development dependencies
      run: |
          pipenv install --dev
    
    - name: Run Unit Tests within pipenv with pytest and generate coverage report
      env:
        AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        AWS_PASSWORD: ${{ secrets.AWS_PASSWORD }}
      run: |
        pipenv run coverage run -m pytest tests --log-cli-level=WARN
        pipenv run coverage report --omit="tests/*" --fail-under=60

    - name: List site-packages
      run: |
        pipenv run python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"

    - name: Install create-dmg for macos
      if: runner.os == 'macOS'
      run: |
        brew install create-dmg

    - name: PyInstaller - Build for ${{ matrix.os }}
      run: |
        cd src
        pipenv run python build.py
      
    - name: Upload Artifact for ${{ matrix.os }}
      uses: actions/upload-artifact@v4
      with:
        name: anonymizer-${{ matrix.os }}-${{ env.version }}
        path: src/dist
        if-no-files-found: error
        retention-days: 1

    - name: Print upload_url
      run:  |
        echo "Upload URL: ${{ needs.release.outputs.upload_url }}"
  

    - name: Upload Release Asset 
      if: "!contains(env.version, 'RC')"
      uses: actions/upload-release-asset@v1
      # continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{ runner.os == 'macOS' && 'src/dist.zip' || 'src/dist.dmg' }}
        asset_name: anonymizer-${{ matrix.os }}-${{ env.version }}.zip
        asset_content_type: application/zip

