# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: anonymizer-test-build-upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: "3.11"

    - name: Install pipenv for virtual environment
      run: |
          pip install pipenv

    - name: Install dependencies including development dependencies
      run: |
          pipenv install --dev
    
    - name: Run Unit Tests within pipenv with pytest and generate coverage report
      run: |
        pipenv run coverage run -m pytest tests --log-cli-level=WARN
        pipenv run coverage report --omit="tests/*" --fail-under=60

    - name: Extract version from version.py
      run: echo "version=$(python -c 'from __version__ import __version__; print(__version__)')" >> $GITHUB_ENV

    - name: List site-packages
      run: |
        pipenv run python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
        
    - name: PyInstaller - Build for ${{ matrix.os }}
      run: |
        pipenv run python build.py
      
    - name: Upload Artifact for ${{ matrix.os }}
      uses: actions/upload-artifact@v4
      with:
        name: anonymizer-${{ matrix.os }}-${{ env.version }}.zip
        path: 'dist'
        compression-level: 9 # best compression
        if-no-files-found: error
        retention-days: 2
      

