name: Tests

on:
  workflow_dispatch:  # Enables manual trigger
  pull_request:
    branches:
      - master
  push: 
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: List files in root
      run: ls -la

    - name: Print working directory
      run: pwd

    - name: Check readme permissions
      run: ls -l readme.md

    - name: Install dependencies
      run: |
        poetry install --with dev --verbose

    - name: Run Unit Tests
      env:
        PYTHONPATH: ${{ github.workspace }}/src
        AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        AWS_PASSWORD: ${{ secrets.AWS_PASSWORD }}
      run: |
        pwd  # Print working directory before running tests
        poetry run test

  